name: ipcambox # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: IpCamBox # 79 char long summary
description: |
  IpCamBox

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ipcambox:
    # See 'snapcraft plugins'
    plugin: cmake
    source-type: git
    source: https://github.com/RSATom/IpCamBox.git
    build-packages:
        - g++
        - make
        - pkg-config
        - libpq-dev
        - libgstrtspserver-1.0-dev
        - libgstreamer1.0-dev
        - libspdlog-dev
        - libprotobuf-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - protobuf-compiler

apps:
  ipcambox:
    command: Test
